import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
        backgroundColor: '#EBF4F6',
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F7FA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E1E8ED',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  menuButton: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#F5F7FA',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#071952',
    marginLeft: 16,
    letterSpacing: 0.5,
  },
  profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 28,
    margin: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
  },
  imageWrapper: {
    position: 'relative',
    marginBottom: 20,
  },
  profileImage: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#E1E8ED',
    borderWidth: 4,
    borderColor: '#FFFFFF',
  },
  profileIcon: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#088395',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
  },
  profileIconText: {
    fontSize: 52,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  imageOverlayButton: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    backgroundColor: '#088395',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  imageOverlayText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '600',
    marginTop: -2,
  },
  profileName: {
    fontSize: 26,
    fontWeight: '700',
    color: '#071952',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  roleLabel: {
    fontSize: 16,
    color: '#088395',
    fontWeight: '600',
    backgroundColor: '#E8F6F8',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 14,
    overflow: 'hidden',
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    margin: 16,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
  },
  infoLabel: {
    fontSize: 15,
    color: '#6B7280',
    marginBottom: 6,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  infoText: {
    fontSize: 17,
    color: '#071952',
    marginBottom: 20,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
});

export default styles;