import { StyleSheet, Dimensions, PixelRatio, Platform } from 'react-native';

const styles = StyleSheet.create({
    routeHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    filterContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      backgroundColor: '#F8FAFC',
      padding: 12,
      borderRadius: 10,
    },
    filterLabel: {
      fontSize: 14,
      color: '#071952',
      marginRight: 12,
      fontWeight: '500',
    },
    filterInput: {
      borderWidth: 1,
      borderColor: '#E2E8F0',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      width: 70,
      fontSize: 14,
      color: '#071952',
      backgroundColor: '#FFFFFF',
      textAlign: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    tripCount: {
      fontSize: 14,
      color: '#64748B',
      fontWeight: '500',
    },
    container: {
      flex: 1,
      backgroundColor: '#EBF4F6',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      backgroundColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderBottomColor: '#E2E8F0',
    },
    backButton: {
      padding: 8,
    },
    headerTitle: {
      marginLeft: 16,
      fontSize: 20,
      fontWeight: '600',
      color: '#071952',
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      padding: 16,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    loadingText: {
      fontSize: 16,
      color: '#64748B',
    },
    chartContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    chartTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#071952',
      marginBottom: 16,
    },
    chart: {
      marginVertical: 8,
      borderRadius: 16,
    },
    routesContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#071952',
      marginBottom: 16,
    },
    routeCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    routeInfo: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 4,
    },
    routeText: {
      fontSize: 15,
      color: '#071952',
      fontWeight: '600',
      flex: 1,
    },
    routeDistance: {
      fontSize: 14,
      color: '#088395',
      fontWeight: '500',
      marginLeft: 12,
    },
    tripCount: {
      fontSize: 14,
      color: '#088395',
      fontWeight: '500',
      backgroundColor: '#EBF4F6',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    noDataText: {
      fontSize: 14,
      color: '#64748B',
      textAlign: 'center',
      padding: 20,
      fontStyle: 'italic',
    },
  });

  export default styles;